const DIALOGS = [
  `Congratulation, you win!`,
  `You did it! Hurray!`,
  `You're simply amazing!`,
  `New record!`,
  `A winner is you!`,
  `Wow! Victory!`,
  `You made the right choices.`,
  `Spectacular! You completed the puzzle.`,
  `So impressive!`,
  `Bravo! You unlocked the last secret!`,
  `This is your lucky day!`,
  `You're learning really fast!`,
  `Achievement unlocked: Legendary Hero`,
  `You are an aspiration to everyone.`,
  `Well done: you did everything.`,
  `ULTRA MASTER COMBO`,
  `We can't hide anything from you, can we?`,
  `Everybody loves you.`,
  `Nothing can stop you!`,
  `You are the master of secrets.`,
  `We couldn't make it without you.`,
  `Your skills are perfect!`,
  `You should consider streaming.`,
  `You are still winning.`,
  `You will probably succeed forever!`,
  `People are worshipping you.`,
  `You are the incarnation of perfection. Don't ever change.`,
  `All your opinions are valid.`,
  `Peaople are nothing compared to you.`,
  `You can't fail. Ever.`,
  `We litterally can't believe you're still doing it.`,
  `You should never stop, really.`,
  `You are so good at it.`,
  `Why would you waste your talent elsewhere?`,
  `Guess what? You win again. Clap clap.`,
  `Fireworks, kiss from the Princess on the cheeks.`,
  `We can't contain our excitement right now.`,
  `You really like beating this game it seems.`,
  `Here is your validation feedback.`,
  `You deserved this victory.`,
  `We expected nothing better from you.`,
  `You officially have found everything.`,
  `Actually, we don't need to remind you that you're winning.`,
  `So good bye. And keep being great!`,
  ``,
  ``,
  ``,
  ``,
  `Now that's a player who looks for secrets!`,
  `So… There were one last. You found it. Yay!`,
  `I guess all those compliments still weren't enough for you?`,
  `Are you trying to reach an official Ending?`,
  `You'll be able to tell your exploit to all your friends.`,
  `They'll be so impressed when they'll learn
  the dedication you put to this game.`,
  `You know perfectly how to manage your time.`,
  `Well, it's going to be your most successful day, isn't it?`,
  `When was the last time you won so much time in a row?`,
  `I mean, you figured it out, you persisted… Cool.`,
  `Yeah, alright, how can I be more clear: THERE IS NOTHING MORE.`,
  `You did it. Like, all of what this game has to offer.`,
  `So, what, you really want me to say The End? Is that it?`,
  `THE END`,
  `Thanks for playing`,
  `Game by Alexandre Pontaise`,
  `All About The Player`,
  `Press Alt+F4 to quit`,
  `…`,
  `Are you so determinated to dig it all?`,
  `Winning isn't enough?`,
  `Perhaps you want to DEFEAT something?`,
  `Fine: I have lost! You outsmarted me.`,
  `Your rank among other players is: #1`,
  `While we're at it: EVERYBODY LOSES BUT YOU!`,
  `Call your friends. They need to know.`,
  `Do you feel superior now? Satisfied?`,
  `What is it you think you can gain more from me?`,
  `I can continue for days, you know.`,
  `It's not like it takes much time to write.`,
  `Do you want to feel special?`,
  `Or is that you really like playing this game?`,
  `Maybe you do the right combination only by accident.`,
  `Maybe this is the only game you can complete.`,
  `Sorry for being mean. I shouldn't.`,
  `YOU GOT APOLOGIES! Are you happy now?`,
  `Well, I mean, it's nice of you to keep playing. I should be thanksful.`,
  `Do you like being called nice?
  What if I tell you're the nicest person ever?`,
  `Like this game where you choose to be aggressive or not.
  This made you the master of empathy!`,
  `You'll sure improve the world with all your wisdom from video games.`,
  `“Don't kill gobelins if they're weak”, what a great lesson you've learned.`,
  `If there is a lesson in this game, you probably learned it already.`,
  `You learned everything. Wow.`,
  `All of that thanks to repeated efforts.`,
  `I feel bad for not offering you anything more.`,
  `You should have had a 3D cinematic already, to honor your greatness.`,
  `But maybe you like just the text?`,
  `Like, you want to remain simple, and humble.`,
  `You're the most humble person in the world by the way.`,
  `Humility and modesty. Those traits define the true hero that you are.`,
  `It was a privilege to meet you.`,
  `Anyway, I'm feeling I'm REALLY wasting your precious time.`,
  `You could save the world, right now.
  With all your power and knowledge.`,
  `So let's just say you've reach the end of my speech. For real, this time.`,
  `I'll just let you win, without useless comentary.
  Maybe that's all you want.`,
  `You'll be fine, I believe in you.`,
  `WIN`
];